name: Build Paragon

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 1.8 Setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle shit
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle
        run: chmod +x gradlew

      - name: Build client
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: Paragon-Build
          path: build/libs/*.jar

